### ISSUE TITLE
Error: [$parse:ueoe] Unexpected end of expression: gotoPage(page

### ISSUE THREAD

**Issue by dnauck** [begriffs/angular-paginate-anything#75]
I have the following error now with Angular 1.3.15 and 1.4.1, any idea what is wrong?

```
Error: [$parse:ueoe] Unexpected end of expression: gotoPage(page
http://errors.angularjs.org/1.4.1/$parse/ueoe?p0=gotoPage(page
    at REGEX_STRING_REGEXP (http://localhost:53875/bower_components/angular/angular.js:68:12)
    at Object.AST.consume (http://localhost:53875/bower_components/angular/angular.js:12872:13)
    at Object.AST.primary (http://localhost:53875/bower_components/angular/angular.js:12775:14)
    at Object.AST.unary (http://localhost:53875/bower_components/angular/angular.js:12748:19)
    at Object.AST.multiplicative (http://localhost:53875/bower_components/angular/angular.js:12735:21)
    at Object.AST.additive (http://localhost:53875/bower_components/angular/angular.js:12726:21)
    at Object.AST.relational (http://localhost:53875/bower_components/angular/angular.js:12717:21)
    at Object.AST.equality (http://localhost:53875/bower_components/angular/angular.js:12708:21)
    at Object.AST.logicalAND (http://localhost:53875/bower_components/angular/angular.js:12700:21)
    at Object.AST.logicalOR (http://localhost:53875/bower_components/angular/angular.js:12692:21) <a href="" ng-click="gotoPage(page-1)">
```

**Comment by begriffs** [comment]
It looks like it is originating in the `ng-click`s inside `src/paginate-anything.html`.

Locally I was just able to run the test suite with Angular 1.4.1 and everything passed. It's not immediately jumping out at me what is going on here. Perhaps try running the html file through a strict linter like https://www.npmjs.com/package/grunt-html-angular-validate

**Comment by dnauck** [comment]
Looks like this issue only occurs in Chrome. I'm using 43.0.2357.132 m (64 bit).

**Comment by AmarJagtapDev** [comment]
**hide this code in ng-grid.js - it add extra column when group is add.**  
/moved out of above loops due to if no data initially, but has initial grouping, columns won't be added/
if(cols.length > 0) {
            for (var z = 0; z < groups.length; z++) {
                if (!cols[z].isAggCol && z <= maxDepth) {
                    cols.push(new ngColumn({
                        colDef: {
                            field: '',
                            width: 25,
                            sortable: false,
                            resizable: false,
                            headerCellTemplate: '<div class="ngAggHeader"></div>',
                            pinned: grid.config.pinSelectionCheckbox
                            
                        },
                        enablePinning: grid.config.enablePinning,
                        isAggCol: true,
                        headerRowHeight: grid.config.headerRowHeight
                        
                    }, $scope, grid, domUtilityService, $templateCache, $utils));
                }
            }
        }
